// "use strict";
// exports.__esModule = true;
// var superHeros = [];
// // const heroPower: number[] = [];
// var heroPower = [];
// superHeros.push("spiderman");
// heroPower.push(21);
// var allUsers = [];
// allUsers.push({ name: "name", isActive: true });
// console.log("all users are: ", allUsers);
